// Code generated by MCHP Chatbot
// R.D.F Discord Bot - Presence tracking for "الأفراد" section
// Tracks online/offline status of members who have the target role.

const { Client, GatewayIntentBits, Events, ActivityType, PermissionsFlagsBits } = require('discord.js');
const { joinVoiceChannel, VoiceConnectionStatus, getVoiceConnection } = require('@discordjs/voice');
const VOICE_CONNECTIONS = new Map(); // channelId -> connection
require('dotenv').config();

const TOKEN = process.env.DISCORD_BOT_TOKEN;
const GUILD_ID = process.env.DISCORD_GUILD_ID;
// The role ID for the "الأفراد" section
const TARGET_ROLE_ID = process.env.TARGET_ROLE_ID || '1534317414521503876';

// Rank role names that map to the rank ladder (optional for display)
const RANK_ROLES = [
  'جندي',
  'عريف',
  'رقيب',
  'مساعد أول',
  'ملازم',
  'نقيب',
  'رائد',
  'مقدم',
  'عقيد',
  'لواء',
];

const client = new Client({
intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMembers,
    GatewayIntentBits.GuildPresences,
    GatewayIntentBits.GuildVoiceStates,
  ],
});

// In-memory store of members with the target role
let membersCache = [];

// Throttle: minimum time between full Discord member fetches to avoid rate limits
let lastRefresh = 0;
const REFRESH_INTERVAL = 20000; // 20 seconds

// Extract members with target role from a guild
function extractMembers(guild) {
  const members = [];
  for (const member of guild.members.cache.values()) {
    if (member.roles.cache.has(TARGET_ROLE_ID)) {
      members.push({
        id: member.user.id,
        username: member.user.username,
        globalName: member.user.globalName || member.user.username,
        avatar: member.user.displayAvatarURL({ size: 128 }),
        displayName: member.displayName || member.user.username,
        status: member.presence?.status || 'offline',
        isOnline:
          member.presence?.status === 'online' ||
          member.presence?.status === 'dnd' ||
          member.presence?.status === 'idle',
      });
    }
  }
  return members;
}

function updateCache(guild) {
  if (guild) membersCache = extractMembers(guild);
}

client.once(Events.ClientReady, async (c) => {
  console.log(`✅ R.D.F Bot logged in as ${c.user.tag}`);

  try {
    const guild = await client.guilds.fetch(GUILD_ID);
    await guild.members.fetch();
    updateCache(guild);
    console.log(`👥 Found ${membersCache.length} members with target role`);
  } catch (err) {
    console.error('❌ Failed to load guild members:', err.message);
  }
});

// Update on presence changes
client.on(Events.PresenceUpdate, async (oldPresence, newPresence) => {
  const guild = newPresence?.guild || oldPresence?.guild;
  if (guild && guild.id === GUILD_ID) {
    updateCache(guild);
  }
});

// Update on member role changes / join
client.on(Events.GuildMemberUpdate, (oldMember, newMember) => {
  if (newMember.guild.id === GUILD_ID) {
    updateCache(newMember.guild);
  }
});

client.on(Events.GuildMemberAdd, (member) => {
  if (member.guild.id === GUILD_ID) {
    updateCache(member.guild);
  }
});

client.on(Events.GuildMemberRemove, (member) => {
  if (member.guild.id === GUILD_ID) {
    updateCache(member.guild);
  }
});

client.on(Events.Warn, (info) => console.warn('Bot warning:', info));
client.on(Events.Error, (err) => console.error('Bot error:', err));

// ---- Admin / role management functions ----

/**
 * Gives the sector role to a member (adds them to the sector).
 * @param {string} memberId - Discord user ID
 */
async function addMemberToSector(memberId) {
  const guild = await client.guilds.fetch(GUILD_ID);
  const member = await guild.members.fetch(memberId);
  if (!member) throw new Error('Member not found in server');
  if (!member.roles.cache.has(TARGET_ROLE_ID)) {
    await member.roles.add(TARGET_ROLE_ID);
  }
  updateCache(guild);
  return { success: true };
}

/**
 * Removes the sector role from a member.
 * @param {string} memberId
 */
async function removeMemberFromSector(memberId) {
  const guild = await client.guilds.fetch(GUILD_ID);
  const member = await guild.members.fetch(memberId);
  if (!member) throw new Error('Member not found in server');
  if (member.roles.cache.has(TARGET_ROLE_ID)) {
    await member.roles.remove(TARGET_ROLE_ID);
  }
  updateCache(guild);
  return { success: true };
}

/**
 * Checks if a member has the target (الأفراد) role.
 * @param {string} memberId - Discord user ID
 * @returns {Promise<boolean>}
 */
async function hasTargetRole(memberId) {
  // Check the cache first to avoid hitting Discord API on every duty check
  if (membersCache.some((m) => String(m.id) === String(memberId))) {
    return true;
  }
  try {
    const guild = await client.guilds.fetch(GUILD_ID);
    const member = await guild.members.fetch({ user: memberId });
    if (!member) return false;
    const has = member.roles.cache.has(TARGET_ROLE_ID);
    // Update cache if they have the role
    if (has) updateCache(guild);
    return has;
  } catch (err) {
    console.error('hasTargetRole error:', err.message);
    return false;
  }
}

/**
 * Sends a DM to a guild member.
 * @param {string} memberId - Discord user ID
 * @param {string} message - The message to send
 * @returns {Promise<boolean>}
 */
async function sendDM(memberId, message) {
  try {
    const guild = await client.guilds.fetch(GUILD_ID);
    // fetch may throw; guard with catch to return null if not found
    const member = await guild.members.fetch({ user: memberId }).catch(() => null);
    if (!member || !member.user) {
      console.warn(`DM skipped: member ${memberId} not found or has no user object`);
      return false;
    }
    const user = member.user;
    if (typeof user.send !== 'function') {
      console.warn(`DM skipped: user ${memberId} does not support DM sending`);
      return false;
    }
    await user.send(message);
    console.log(`📨 DM sent to user ${memberId}`);
    return true;
  } catch (err) {
    console.error(`DM failed to ${memberId}:`, err && err.message ? err.message : err);
    return false;
  }
}

/**
 * Lists all guild members (for the admin panel dropdown).
 */
async function listGuildMembers() {
  const guild = await client.guilds.fetch(GUILD_ID);
  await guild.members.fetch();
  const members = [];
  for (const m of guild.members.cache.values()) {
    if (m.user.bot) continue;
    members.push({
      id: m.user.id,
      username: m.user.username,
      displayName: m.displayName || m.user.username,
      avatar: m.user.displayAvatarURL({ size: 128 }),
      inSector: m.roles.cache.has(TARGET_ROLE_ID),
      /** Highest rank role name if any rank role is assigned */
      rankRole: m.roles.cache.find((r) => RANK_ROLES.includes(r.name))?.name || null,
    });
  }
  return members;
}


// ---- Directed voice (دخول موجه) ----

/** Ensures a directed voice channel exists and returns it (creates if missing). */
async function ensureDirectedChannel(guild, number) {
  const channelName = `موجه ${number}`;
  let channel = guild.channels.cache.find((c) => c.type === 2 && c.name === channelName);
  if (!channel) {
    channel = await guild.channels.create({
      name: channelName,
      type: 2, // GuildVoice
      // videoQualityMode: 'auto',
    });
  }
  return channel;
}

/** Ensures the bot's dedicated voice channel exists (number -1). */
async function ensureBotVoiceChannel(guild) {
  const channelName = 'موجه -1';
  let channel = guild.channels.cache.find((c) => c.type === 2 && c.name === channelName);
  if (!channel) {
    channel = await guild.channels.create({
      name: channelName,
      type: 2, // GuildVoice
    });
  }
  return channel;
}

/** Connects the bot to a voice channel (returns the connection). */
function connectToVoice(channelId, guild) {
  const existing = getVoiceConnection(guild.id);
  if (existing && existing.joinConfig.channelId === channelId) return existing;
  if (existing) existing.destroy();
  const connection = joinVoiceChannel({
    channelId,
    guildId: guild.id,
    adapterCreator: guild.voiceAdapterCreator,
    selfDeaf: false,
    selfMute: true,
  });
  VOICE_CONNECTIONS.set(channelId, connection);
  return connection;
}

/**
 * Moves a member into a directed voice room by number.
 * @param {string} memberId - Discord user ID
 * @param {number} number - Directed number (1-100)
 */
async function joinDirectedVoice(memberId, number) {
  const n = parseFloat(number);
  if (isNaN(n) || n < 1 || n > 100) {
    throw new Error('يجب أن يكون الرقم بين 1 و 100');
  }
  const guild = await client.guilds.fetch(GUILD_ID);
  let member;
  try {
    member = await guild.members.fetch(memberId);
  } catch (e) {
    throw new Error('العضو غير موجود في السيرفر');
  }
  if (!member) throw new Error('العضو غير موجود في السيرفر');

const channel = await ensureDirectedChannel(guild, n);

  // Make the directed channel private so ONLY this member can see/join it
  try {
    // Deny visibility to @everyone first
    await channel.permissionOverwrites.set([
      {
        id: guild.roles.everyone.id,
        deny: [PermissionsFlagsBits.ViewChannel, PermissionsFlagsBits.Connect],
      },
      // Allow only the target member to view and connect
      { id: memberId, allow: [PermissionsFlagsBits.ViewChannel, PermissionsFlagsBits.Connect] },
    ]);
  } catch (e) {
    // If permission update fails, continue moving the member anyway
    console.error('Set directed channel permissions failed:', e.message);
  }

  // Connect the bot to its own dedicated voice channel (موجه -1) instead of the member's channel
  const botChannel = await ensureBotVoiceChannel(guild);
  connectToVoice(botChannel.id, guild);

  // Wait a short moment for the voice connection to be ready
  await new Promise((r) => setTimeout(r, 700));

  try {
    await member.voice.setChannel(channel.id);
  } catch (e) {
    throw new Error('تعذر نقل العضو إلى الروم الصوتي. تأكد من أن العضو متصل بروم صوتي وأن البوت لديه صلاحية النقل (Connect/Move Members).');
  }

  return { success: true, number: n, channelId: channel.id, channelName: channel.name };
}

/** Removes a member from any directed voice room. */
async function leaveDirectedVoice(memberId) {
  const guild = await client.guilds.fetch(GUILD_ID);
  let member;
  try {
    member = await guild.members.fetch(memberId);
  } catch (e) {
    return { success: true };
  }
  if (member.voice && member.voice.channelId) {
    try {
      await member.voice.disconnect();
    } catch (e) {
      // ignore - member may not be connected
    }
  }
  return { success: true };
}

// Allow replacing the default voice adapter
client.guilds.cache.forEach?.((g) => {});

// Manage directed voice channel visibility: only visible to people inside it, and locked.
client.on(Events.VoiceStateUpdate, async (oldState, newState) => {
  const guild = newState?.guild || oldState?.guild;
  if (!guild || guild.id !== GUILD_ID) return;

  const isDirectedChannel = (ch) => {
    if (!ch) return false;
    const name = ch.name || '';
    return ch.type === 2 && /^موجه \d+(\.\d+)?$/.test(name);
  };

  // Determine if a member joined or left a directed channel
  let joinedChannel = null;
  let leftChannel = null;
  if (newState.channelId && isDirectedChannel(newState.channel)) joinedChannel = newState.channel;
  if (oldState.channelId && isDirectedChannel(oldState.channel)) leftChannel = oldState.channel;
  if (!joinedChannel && !leftChannel) return;

  try {
    // ---- Member joined a directed channel: grant them access (channel stays locked for others) ----
    if (joinedChannel) {
      await joinedChannel.permissionOverwrites.edit(newState.id, {
        ViewChannel: true,
        Connect: true,
      });
      // Make sure @everyone stays denied (locked)
      await joinedChannel.permissionOverwrites.edit(guild.roles.everyone.id, {
        ViewChannel: false,
        Connect: false,
      });
    }

    // ---- Member left a directed channel: revoke their access ----
    if (leftChannel) {
      // Revoke the member's permission to view/connect
      await leftChannel.permissionOverwrites.delete(oldState.id).catch(() => {});
    }

    // ---- If everyone left the channel, delete it ----
    const channelsToCheck = joinedChannel || leftChannel;
    if (channelsToCheck && channelsToCheck.type === 2) {
      const hasHumans = channelsToCheck.members.some((m) => !m.user.bot);
      if (!hasHumans) {
        await channelsToCheck.delete(`Directed voice emptied - ${channelsToCheck.name}`);
        console.log(`🗑️ Deleted directed voice channel: ${channelsToCheck.name}`);
      }
    }
  } catch (err) {
    console.error('Directed voice permission update failed:', err.message);
  }
});

// ---- Exported functions ----

/** Returns cached members with target role. */
function getMembers() {
  return membersCache;
}

/** Refresh the cache from guild. Throttled to avoid Discord rate limits. */
async function refresh(force = false) {
  const now = Date.now();
  // If not forcing and we refreshed recently, return cached data without hammering API
  if (!force && now - lastRefresh < REFRESH_INTERVAL) {
    return membersCache;
  }
  try {
    const guild = await client.guilds.fetch(GUILD_ID);
    await guild.members.fetch();
    updateCache(guild);
    lastRefresh = Date.now();
    return membersCache;
  } catch (err) {
    console.error('Refresh error:', err.message);
    return membersCache;
  }
}

module.exports = {
  client,
  getMembers,
  refresh,
  listGuildMembers,
  addMemberToSector,
  removeMemberFromSector,
  hasTargetRole,
sendDM,
  joinDirectedVoice,
  leaveDirectedVoice,
  isReady: () => client.isReady(),
};

// If run directly, start bot
if (require.main === module) {
  if (!TOKEN) {
    console.error('❌ DISCORD_BOT_TOKEN is not set in .env file');
    process.exit(1);
  }
client.login(TOKEN);
}

