// Code generated by MCHP Chatbot
// LSPD Server
// Express server handling Discord OAuth login, sessions, and API endpoints.
// Uses SQLite database for data storage.

const express = require('express');
const session = require('express-session');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const fetch = require('node-fetch');
require('dotenv').config({ path: require('path').join(__dirname, '.env') });
const db = require('./db');
const bot = require('./bot');
const { liveReload } = require('./live-reload');

const app = express();
const PORT = Number(process.env.PORT) || 3000;

app.use(express.static('public'));

// Enable live-reload (auto-refresh browser on code change)
liveReload(app);

// ---- Config ----
const CLIENT_ID = process.env.DISCORD_CLIENT_ID;
const CLIENT_SECRET = process.env.DISCORD_CLIENT_SECRET;
const REDIRECT_URI = process.env.REDIRECT_URI || 'http://localhost:3001/api/auth/callback';
const GUILD_ID = process.env.DISCORD_GUILD_ID;
const INVITE = process.env.DISCORD_INVITE || 'https://discord.gg/TF6E5jUXXx';

// Admin (leader) IDs who can write
const ADMIN_IDS = (process.env.ADMIN_IDS || '')
  .split(',')
  .map((id) => id.trim())
  .filter(Boolean);

// ---- Ensure uploads folder ----
const UPLOAD_DIR = path.join(__dirname, 'uploads');
if (!fs.existsSync(UPLOAD_DIR)) {
  fs.mkdirSync(UPLOAD_DIR, { recursive: true });
}

// ---- Middleware ----
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, 'public')));
app.use('/uploads', express.static(UPLOAD_DIR));

// Render/production runs behind a reverse proxy, so trust its HTTPS proxy headers.
app.set('trust proxy', 1);

app.use(
  session({
    secret: process.env.SESSION_SECRET || 'secret',
    resave: false,
    saveUninitialized: false,
    cookie: {
      maxAge: 1000 * 60 * 60 * 24, // 1 day
      httpOnly: true,
      sameSite: 'lax',
      secure: process.env.NODE_ENV === 'production',
    },
  })
);

// Multer for file uploads (images)
const upload = multer({
  storage: multer.diskStorage({
    destination: UPLOAD_DIR,
    filename: (req, file, cb) => {
      const ext = path.extname(file.originalname) || '.png';
      cb(null, `${Date.now()}-${Math.random().toString(36).slice(2, 8)}${ext}`);
    },
  }),
  limits: { fileSize: 5 * 1024 * 1024 }, // 5MB
});

// ---- OAuth endpoints ----

// Redirect to Discord OAuth
app.get('/api/auth/discord', (req, res) => {
  const scope = encodeURIComponent('identify');
  const redirect = encodeURIComponent(REDIRECT_URI);
  res.redirect(
    `https://discord.com/api/oauth2/authorize?client_id=${CLIENT_ID}&redirect_uri=${redirect}&response_type=code&scope=${scope}`
  );
});

// OAuth callback
app.get('/api/auth/callback', async (req, res) => {
  const code = req.query.code;
  if (!code) return res.redirect('/?error=auth_failed');

  try {
    const tokenRes = await fetch('https://discord.com/api/oauth2/token', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        client_id: CLIENT_ID,
        client_secret: CLIENT_SECRET,
        grant_type: 'authorization_code',
        code,
        redirect_uri: REDIRECT_URI,
      }),
    });

    const tokenData = await tokenRes.json();
    if (!tokenData.access_token) {
      return res.redirect('/?error=auth_failed');
    }

    // Fetch user info
    const userRes = await fetch('https://discord.com/api/users/@me', {
      method: 'GET',
      headers: { Authorization: `Bearer ${tokenData.access_token}` },
    });
    if (!userRes.ok) {
      console.error('Failed to fetch Discord user info:', await userRes.text());
      return res.redirect('/?error=auth_failed');
    }
    const user = await userRes.json();

    // The site is restricted to members of the configured Discord server.
    // The bot checks membership server-side so this cannot be bypassed by editing the browser.
    if (!GUILD_ID || !bot.isReady()) {
      console.error('OAuth callback: Discord bot is not ready or GUILD_ID is missing.');
      return res.redirect('/?error=service_unavailable');
    }

    const isInGuild = await bot.isGuildMember(user.id);
    if (!isInGuild) {
      return res.redirect('/?error=not_in_guild');
    }

    // Store session
    req.session.user = {
      id: user.id,
      username: user.username,
      global_name: user.global_name || user.username,
      avatar: user.avatar
        ? `https://cdn.discordapp.com/avatars/${user.id}/${user.avatar}.png`
        : `https://cdn.discordapp.com/embed/avatars/${(BigInt(user.id) >> 22n) % 6n}.png`,
      isInGuild,
      isAdmin: ADMIN_IDS.includes(user.id),
    };

    req.session.save(() => res.redirect('/dashboard.html'));
  } catch (err) {
    console.error('OAuth callback error:', err);
    res.redirect('/?error=auth_failed');
  }
});

// Logout
app.get('/api/auth/logout', (req, res) => {
  req.session.destroy(() => {
    res.redirect('/');
  });
});

// Get current user
app.get('/api/user', (req, res) => {
  if (req.session.user) {
    res.json({ user: req.session.user, isAdmin: req.session.user.isAdmin });
  } else {
    res.json({ user: null });
  }
});

// ---- Auth middleware ----
function requireAuth(req, res, next) {
  if (!req.session.user) {
    return res.status(401).json({ error: 'Not authenticated' });
  }
  next();
}

function requireAdmin(req, res, next) {
  if (!req.session.user) {
    return res.status(401).json({ error: 'Not authenticated' });
  }
  if (!req.session.user.isAdmin) {
    return res.status(403).json({ error: 'You do not have permission to write' });
  }
  next();
}

// ---- DM message helpers ----

// Format current date/time in Arabic
function formatDateTime() {
  const now = new Date();
  const date = now.toLocaleDateString('ar-SA', { year: 'numeric', month: 'long', day: 'numeric' });
  const time = now.toLocaleTimeString('ar-SA', { hour: '2-digit', minute: '2-digit' });
  return `${date} - ${time}`;
}

// Build a DM message header with responsible admin mention, member mention, and timestamp
function dmHeader(adminId, memberId, title) {
  return '━━━━━━━━━━━━━━━━━━\n📋 **' + title + '**\n━━━━━━━━━━━━━━━━━━\n👤 **المسؤول:** <@' + adminId + '>\n🎯 **الفرد:** <@' + memberId + '>\n🕐 **الوقت:** ' + formatDateTime() + '\n━━━━━━━━━━━━━━━━━━\n';
}

// Log an admin action to the سجل الحركات (log)
function logAction(req, action, targetName, targetId, details) {
  try {
    db.addLog({
      action,
      adminName: req.session.user.global_name || req.session.user.username,
      adminId: req.session.user.id,
      targetName,
      targetId,
      details,
    });
  } catch (err) {
    console.error('Log error:', err.message);
  }
}

// ---- API endpoints ----

// SECTOR DATA
app.get('/api/sector', requireAuth, (req, res) => {
  try {
    res.json({ records: db.getSector() });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/sector', requireAdmin, (req, res) => {
  try {
    const { name, rank } = req.body;
    if (!name || !rank) return res.status(400).json({ error: 'Name and rank are required' });
const record = db.addSector({
      name,
      rank,
      addedBy: req.session.user.username,
      addedById: req.session.user.id,
    });
    logAction(req, 'إضافة بيانات قطاع', name, '', 'الرتبة: ' + rank);
    res.json({ record });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.delete('/api/sector/:id', requireAdmin, (req, res) => {
  try {
    const result = db.deleteSector(req.params.id, req.session.user.id);
    if (!result.success) {
      return res.status(result.error === 'not_found' ? 404 : 403).json({ error: 'لا يمكنك حذف هذا السجل' });
    }
        logAction(req, 'حذف بيانات قطاع 🗑️', '', req.params.id, 'حذف سجل من بيانات القطاع');
res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// VEHICLES
app.get('/api/vehicles', requireAuth, (req, res) => {
  try {
    res.json({ records: db.getVehicles() });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/vehicles', requireAdmin, upload.single('photo'), (req, res) => {
  try {
    const { name, color } = req.body;
    if (!name || !color) return res.status(400).json({ error: 'Car name and color are required' });

    const photoUrl = req.file ? `/uploads/${req.file.filename}` : null;

const record = db.addVehicle({
      name,
      color,
      photo: photoUrl,
      addedBy: req.session.user.username,
      addedById: req.session.user.id,
    });
    logAction(req, 'إضافة مركبة', name, '', 'اللون: ' + color);
    res.json({ record });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.delete('/api/vehicles/:id', requireAdmin, (req, res) => {
  try {
    const result = db.deleteVehicle(req.params.id, req.session.user.id);
    if (!result.success) {
      return res.status(result.error === 'not_found' ? 404 : 403).json({ error: 'لا يمكنك حذف هذا السجل' });
    }
        logAction(req, 'حذف مركبة 🗑️', '', req.params.id, 'حذف سجل مركبة');
res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// WANTED LIST
app.get('/api/wanted', requireAuth, (req, res) => {
  try {
    res.json({ records: db.getWanted() });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/wanted', requireAdmin, upload.single('photo'), (req, res) => {
  try {
    const { name, charge, danger } = req.body;
    if (!name || !charge || !danger) {
      return res.status(400).json({ error: 'Name, charge, and danger level are required' });
    }

    const photoUrl = req.file ? `/uploads/${req.file.filename}` : null;

const record = db.addWanted({
      name,
      charge,
      danger,
      photo: photoUrl,
      addedBy: req.session.user.username,
      addedById: req.session.user.id,
    });
    logAction(req, 'إضافة مطلوب', name, '', 'التهمة: ' + charge + ' | الدرجة: ' + danger);
    res.json({ record });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.delete('/api/wanted/:id', requireAdmin, (req, res) => {
  try {
    const result = db.deleteWanted(req.params.id, req.session.user.id);
    if (!result.success) {
      return res.status(result.error === 'not_found' ? 404 : 403).json({ error: 'لا يمكنك حذف هذا السجل' });
    }
        logAction(req, 'حذف مطلوب 🗑️', '', req.params.id, 'حذف سجل مطلوب');
res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// MEMBERS (الأفراد) - presence tracking (public, no login required)
app.get('/api/members', async (req, res) => {
  try {
    // Refresh cache to get latest presence
    await bot.refresh();
    const members = bot.getMembers();
    const onDutyIds = db.getOnDutyIds();
    const dutyList = db.getDuty();
    const enriched = members.map((m) => {
      const isOnDuty = onDutyIds.includes(String(m.id));
      const dutyInfo = dutyList.find((d) => String(d.member_id) === String(m.id));
      return {
        ...m,
        isOnDuty,
        dutyTime: dutyInfo ? dutyInfo.loginTime : null,
      };
    });
    res.json({ members: enriched, botReady: bot.isReady() });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ---- DUTY (تسجيل دخول للخدمة) ----

// Get current user's duty status
// Also returns whether the user has the "الأفراد" role (can join duty)
app.get('/api/duty/me', requireAuth, async (req, res) => {
  try {
    const isOnDuty = db.isOnDuty(req.session.user.id);
    const hasRole = await bot.hasTargetRole(req.session.user.id);
    res.json({ isOnDuty, hasRole, userId: req.session.user.id });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Login to duty (تسجيل دخول للخدمة) - only for members with الأفراد role
app.post('/api/duty/login', requireAuth, async (req, res) => {
  try {
    const hasRole = await bot.hasTargetRole(req.session.user.id);
    if (!hasRole) {
      return res.status(403).json({ error: 'ليس لديك صلاحية تسجيل الدخول للخدمة' });
    }
    const result = db.setOnDuty({
      memberId: req.session.user.id,
      memberName: req.session.user.global_name || req.session.user.username,
      addedBy: req.session.user.username,
    });
    res.json({ success: true, duty: result.duty });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Logout from duty (خروج من الخدمة)
app.post('/api/duty/logout', requireAuth, (req, res) => {
  try {
    db.setOffDuty(req.session.user.id);
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ---- DIRECTED VOICE (دخول موجه) ----

// Get current user's directed voice status
app.get('/api/directed/me', requireAuth, async (req, res) => {
  try {
    const entry = db.getDirectedByMember(req.session.user.id);
    const hasRole = await bot.hasTargetRole(req.session.user.id);
    res.json({
      inDirected: Boolean(entry),
      number: entry ? entry.number : null,
      hasRole,
      userId: req.session.user.id,
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Join a directed voice room by number (1-100, supports decimals like 89.3)
app.post('/api/directed/join', requireAuth, async (req, res) => {
  try {
    const { number } = req.body;
    if (number === undefined || number === null || number === '') {
      return res.status(400).json({ error: 'الرجاء إدخال رقم' });
    }
    const n = parseFloat(number);
    if (isNaN(n) || n < 1 || n > 100) {
      return res.status(400).json({ error: 'يجب أن يكون الرقم بين 1 و 100' });
    }

    // Only members with the الأفراد role can join directed voice
    const hasRole = await bot.hasTargetRole(req.session.user.id);
    if (!hasRole) {
      return res.status(403).json({ error: 'ليس لديك صلاحية الدخول الموجه' });
    }

    // Move the member into the directed voice channel
    const result = await bot.joinDirectedVoice(req.session.user.id, n);

    // Record the directed entry in db
    db.setDirected({
      memberId: req.session.user.id,
      memberName: req.session.user.global_name || req.session.user.username,
      number: String(n),
    });

    res.json({ success: true, number: n, channelName: result.channelName });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Leave directed voice
app.post('/api/directed/leave', requireAuth, async (req, res) => {
  try {
    await bot.leaveDirectedVoice(req.session.user.id);
    db.clearDirected(req.session.user.id);
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ---- ADMIN PANEL (leaders only) ----

// List all sector members (from Discord role + db merge)
app.get('/api/admin/members', requireAdmin, async (req, res) => {
  try {
    // Refresh the bot cache to get the current members with the LSPD role
    await bot.refresh();
    const roleMembers = bot.getMembers(); // members with target role in Discord
    const dbMembers = db.getMembers();    // db records (rank, warnings)
    const warnings = db.getWarnings();

    // Merge: use Discord role members as the source of truth, fall back to db for rank
    const merged = roleMembers.map((m) => {
      const dbRec = dbMembers.find((x) => String(x.id) === String(m.id));
      const w = warnings.filter((x) => String(x.member_id) === String(m.id));
      return {
        id: String(m.id),
        name: m.displayName || m.username || (dbRec ? dbRec.name : ''),
        rank: dbRec ? dbRec.rank : 'جندي',
        rankIndex: dbRec ? dbRec.rankIndex : 0,
        avatar: m.avatar || '',
        isOnline: m.isOnline,
        added_by: dbRec ? dbRec.added_by : '',
        warnings: w,
        warningCount: w.length,
        maxWarnings: db.MAX_WARNINGS,
        threatened: w.length >= db.MAX_WARNINGS - 1,
        removeReady: w.length >= db.MAX_WARNINGS,
      };
    });

    // Also include db members that might not have the role fetched yet
    const roleIds = new Set(roleMembers.map((m) => String(m.id)));
    dbMembers.forEach((m) => {
      if (!roleIds.has(String(m.id))) {
        const w = warnings.filter((x) => String(x.member_id) === String(m.id));
        merged.push({
          id: String(m.id),
          name: m.name,
          rank: m.rank,
          rankIndex: m.rankIndex,
          avatar: '',
          isOnline: false,
          added_by: m.added_by,
          warnings: w,
          warningCount: w.length,
          maxWarnings: db.MAX_WARNINGS,
          threatened: w.length >= db.MAX_WARNINGS - 1,
          removeReady: w.length >= db.MAX_WARNINGS,
        });
      }
    });

    res.json({ members: merged });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// List all Discord guild members (for adding new members)
app.get('/api/admin/guild-members', requireAdmin, async (req, res) => {
  try {
    const guildMembers = await bot.listGuildMembers();
    res.json({ members: guildMembers });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Add a member to the sector (assign role in Discord + add to db)
app.post('/api/admin/members', requireAdmin, async (req, res) => {
  try {
    const { id, name, rank } = req.body;
    if (!id || !name || !rank) return res.status(400).json({ error: 'ID, name, and rank are required' });

    // Give the sector role in Discord
    try {
      await bot.addMemberToSector(id);
    } catch (err) {
      // If the member isn't in the server, still add them to db? Warn but continue.
      return res.status(400).json({ error: 'تعذر إضافة العضو في السيرفر: ' + err.message });
    }

    const result = db.addMember({ id, name, rank, addedBy: req.session.user.username });
    if (!result.success && result.error === 'exists') {
      return res.status(400).json({ error: 'العضو موجود بالفعل في القطاع' });
    }
    logAction(req, 'إضافة فرد ➕', name, id, 'الرتبة: ' + rank);
    res.json({ member: result.member });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Remove a member from the sector (remove role in Discord + remove from db)
app.delete('/api/admin/members/:id', requireAdmin, async (req, res) => {
  try {
    await bot.removeMemberFromSector(req.params.id);
    const result = db.removeMember(req.params.id);
    if (!result.success) {
      return res.status(404).json({ error: 'العضو غير موجود' });
    }
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Helper: ensure a member record exists in db (auto-add from Discord role if missing)
async function ensureMemberInDb(id) {
  const existing = db.getMembers().find((m) => String(m.id) === String(id));
  if (existing) return existing;
  // Try to get name from bot cache
  const botMember = bot.getMembers().find((m) => String(m.id) === String(id));
  const name = botMember ? (botMember.displayName || botMember.username) : String(id);
  const result = db.addMember({ id, name, rank: 'جندي', addedBy: 'system' });
  return result.success ? result.member : null;
}

// Promote a member (increase rank)
app.post('/api/admin/members/:id/promote', requireAdmin, async (req, res) => {
  try {
    await ensureMemberInDb(req.params.id);
    const result = db.promoteMember(req.params.id);
    if (!result.success) {
      return res.status(result.error === 'not_found' ? 404 : 400).json({ error: result.error === 'max_rank' ? 'وصل لأعلى رتبة' : 'العضو غير موجود' });
    }
    // Send DM to the promoted member
    bot.sendDM(
      req.params.id,
      dmHeader(req.session.user.id, req.params.id, 'ترقية 🎖️') +
        'تمت **ترقيتك** في قطاع LSPD إلى رتبة **' + result.member.rank + '**\n\nمن قبل: <@' + req.session.user.id + '>'
    );
    logAction(req, 'ترقية 🎖️', '', req.params.id, 'ترقية فرد');
    res.json({ member: result.member });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Demote a member (decrease rank)
app.post('/api/admin/members/:id/demote', requireAdmin, async (req, res) => {
  try {
    await ensureMemberInDb(req.params.id);
    const result = db.demoteMember(req.params.id);
    if (!result.success) {
      return res.status(result.error === 'not_found' ? 404 : 400).json({ error: result.error === 'min_rank' ? 'وصل لأدنى رتبة' : 'العضو غير موجود' });
    }
    // Send DM to the demoted member
    bot.sendDM(
      req.params.id,
      dmHeader(req.session.user.id, req.params.id, 'تنزيل رتبة 📉') +
        'تم **تنزيل رتبتك** في قطاع LSPD إلى رتبة **' + result.member.rank + '**\n\nمن قبل: <@' + req.session.user.id + '>'
    );
    logAction(req, 'تنزيل رتبة 📉', '', req.params.id, 'تنزيل رتبة فرد');
    res.json({ member: result.member });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Set a member's rank directly
app.post('/api/admin/members/:id/rank', requireAdmin, async (req, res) => {
  try {
    const { rank } = req.body;
    if (!rank) return res.status(400).json({ error: 'Rank is required' });
    const result = db.setMemberRank(req.params.id, rank);
    if (!result.success) {
      return res.status(404).json({ error: 'العضو غير موجود' });
    }
    res.json({ member: result.member });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ---- Warnings ----
// Get warnings for a member
app.get('/api/admin/warnings/:memberId', requireAdmin, (req, res) => {
  try {
    const warnings = db.getWarningsForMember(req.params.memberId);
    res.json({ warnings, max: db.MAX_WARNINGS });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Add a warning to a member
app.post('/api/admin/warnings', requireAdmin, async (req, res) => {
  try {
    const { memberId, reason } = req.body;
    if (!memberId || !reason) return res.status(400).json({ error: 'Member and reason are required' });
    const result = db.addWarning({ memberId, reason, addedBy: req.session.user.username });
    // Send DM about the warning
    bot.sendDM(
      memberId,
      dmHeader(req.session.user.id, memberId, 'إضافة تحذير ⚠️') +
        'تم **إضافة تحذير** لك في قطاع LSPD **(' + result.count + '/' + result.max + ')**\n> 🗒️ **السبب:** ' + reason + '\n\nالمسؤول: <@' + req.session.user.id + '>'
    );
    logAction(req, 'إضافة تحذير ⚠️', '', memberId, 'السبب: ' + reason);
    // At the 2nd warning, warn the member they are threatened with dismissal (مهدد بالفصل)
    if (result.threatened && result.count < result.max) {
      bot.sendDM(
        memberId,
        dmHeader(req.session.user.id, memberId, 'مهدد بالفصل ⚠️⚠️') +
          '🚨 **مهدد بالفصل!** لديك ' + result.count + '/' + result.max + ' تحذيرات.\nإذا وصلت إلى ' + result.max + ' تحذيرات سيتم فصلك من القطاع.\n\nالمسؤول: <@' + req.session.user.id + '>'
      );
    }
    // At the 3rd warning, do NOT auto-remove. Show the admin a "فصل الفرد" button.
    const removeReady = result.removeReady || false;
    return res.json({
      warning: result.warning,
      count: result.count,
      max: result.max,
      threatened: result.threatened || false,
      removeReady,
      removed: false,
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Dismiss (فصل) a member manually - removes role from Discord + db record + warnings
app.post('/api/admin/members/:id/dismiss', requireAdmin, async (req, res) => {
  try {
    // Remove the Discord role
    await bot.removeMemberFromSector(req.params.id);
    // Remove from db
    db.removeMember(req.params.id);
    // Clear warnings for this member
    db.clearWarnings(req.params.id);
    // Send DM to the dismissed member
    bot.sendDM(
      req.params.id,
      dmHeader(req.session.user.id, req.params.id, 'فصل من القطاع 🚫') +
        '🚫 تم **فصلك** من قطاع LSPD وتم إزالة رتبتك.\n\nالمسؤول: <@' + req.session.user.id + '>'
    );
    logAction(req, 'فصل من القطاع 🚫', '', req.params.id, 'فصل فرد من القطاع');
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Remove a warning
app.delete('/api/admin/warnings/:id', requireAdmin, async (req, res) => {
  try {
    const warning = db.getWarnings().find((w) => String(w.id) === String(req.params.id));
    const result = db.removeWarning(req.params.id);
    if (!result.success) return res.status(404).json({ error: 'التحذير غير موجود' });
    if (warning) {
      bot.sendDM(
        warning.member_id,
        dmHeader(req.session.user.id, warning.member_id, 'إزالة تحذير ✅') +
          '✅ تم **إزالة تحذير** من سجلك في قطاع LSPD.\n\nالمسؤول: <@' + req.session.user.id + '>'
      );
      logAction(req, 'إزالة تحذير ✅', '', warning.member_id, '');
    }
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Clear all warnings for a member
app.delete('/api/admin/warnings/member/:memberId', requireAdmin, (req, res) => {
  try {
    db.clearWarnings(req.params.memberId);
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Get the rank ladder
app.get('/api/admin/ranks', requireAdmin, (req, res) => {
  try {
    res.json({ ranks: db.RANKS, maxWarnings: db.MAX_WARNINGS });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// LOG (سجل الحركات) - admin only
app.get('/api/log', requireAdmin, (req, res) => {
  try {
    res.json({ logs: db.getLogs() });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Health check
app.get('/api/health', (req, res) => {
  res.json({ ok: true, botReady: bot.isReady() });
});

// ---- Uniform (ملابس) section ----
app.get('/api/uniform', (req, res) => {
  res.json({
    uniforms: [
      {
        id: 1,
        role: 'الخفيف الافراد',
        title: 'طقم <:RDF:1534586119692353567> الخفيف الافراد',
        tshirt: '47-70',
        pants: '4-24',
        armor: '63-41',
        shoes: '1-67',
        glasses: '2-34',
        gloves: '7-60',
        mask: 'الماسك الي موضح بالصورة',
        instructions: 'اخيراً تروح محل اسلحه وتروح عند السماعات  بعدين اول وحده وبس',
        approval: 'تم ترسيم الملابس من قبل F-1  F-2',
        image: '/uploads/7.jpg',
      },
      {
        id: 2,
        role: 'الخفيف الضباط',
        title: 'طقم <:RDF:1534586119692353567> الخفيف الضباط',
        tshirt: '47-70',
        pants: '4-24',
        armor: '63-59',
        shoes: '1-67',
        glasses: '2-34',
        gloves: '7-60',
        mask: 'الماسك الي موضح بالصورة',
        instructions: 'اخيراً تروح محل اسلحه وتروح عند السماعات  بعدين اول وحده وبس',
        approval: 'تم ترسيم الملابس من قبل F-1  F-2',
        image: '/uploads/8.jpg',
      }
    ],
    note: 'قسم الملابس الرسمي - للإستفسار تواصل مع F-1/F-2، الصور والأرقام حسب التحديث الأخير.'
  });
});
// ---- Start ----
function start() {
  if (!CLIENT_ID || !CLIENT_SECRET) {
    console.error('❌ Missing Discord credentials. Set DISCORD_CLIENT_ID and DISCORD_CLIENT_SECRET in the environment.');
    process.exit(1);
  }

  // Login the bot (optional but needed for presence tracking)
  if (process.env.DISCORD_BOT_TOKEN) {
    bot.client.login(process.env.DISCORD_BOT_TOKEN).then(() => {
      console.log('✅ Presence bot connected');
    }).catch((err) => {
      console.error('❌ Bot login failed:', err.message);
    });
  } else {
    console.warn('⚙️ DISCORD_BOT_TOKEN not set - presence tracking disabled');
  }

  app.listen(PORT, () => {
    console.log(`🚀 LSPD server running at http://localhost:${PORT}`);
    console.log(`   OAuth login URL: http://localhost:${PORT}/api/auth/discord`);
  });
}

start();

